BOT_TOKEN = "SIZNING_BOT_TOKEN"
ADMINS = [123456789]  # admin telegram ID

PAYME_MERCHANT_ID = "SIZNING_PAYME_ID"
PAYME_SECRET_KEY = "SIZNING_PAYME_SECRET"
PAYME_CALLBACK_URL = "https://yourserver.com/payme_callback"
